### ISSUE TITLE
import load error with Python 3.6

### ISSUE THREAD

**Issue by fizwit** [paulgriffiths/pyastro#1]
import pyastro
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/easybuild/software/Python/3.6.1-foss-2016b-fh1/lib/python3.6/site-packages/pyastro/__init__.py", line 13, in <module>
    from functions import julian_date, UTC, kepler
ModuleNotFoundError: No module named 'functions'

**Comment by paulgriffiths** [comment]
Fundamental issue is due to installing this with Python 3, when this is a Python 2 library. Specific issue is due to relative imports, which were removed in Python 3. Real fix is to make this library compatible with Python 3. Will close this issue and open a broader one.

**Comment by paulgriffiths** [comment]
Refer to [new issue](https://github.com/paulgriffiths/pyastro/issues/2).
